### ISSUE TITLE
Resolve depencies using paket

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/elmish#76] opened 2017-04-13 13:25 UTC
@forki pointed me that thus dependencies are resolve by nuget.

```fs
<ItemGroup>
  <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
  <PackageReference Include="FSharp.Core" Version="4.1.*" />
  <PackageReference Include="Fable.Core" Version="1.0.0-narumi-*" />
  <DotNetCliToolReference Include="dotnet-fable" Version="1.0.0-narumi-*" />
</ItemGroup>
```

We should use paket with a `.lock` file.

**Comment by forki** [comment] 2017-04-13 14:14
@alfonsogarciacaro @et1975 what do you guys think?

**Comment by alfonsogarciacaro** [comment] 2017-04-13 15:07
Hmmm, I think it's a bit overkill to use Paket for those 2 dependencies (I think the CLI tool and FSharp.NET.Sdk would still need to be in the project file) taking into account that Fable projects won't use any other Nuget dependency. I will undoubtedly use it for server-client projects like the fable-suave-scaffold (which we should make into a template soon).

But of course, if you think this is a good opportunity to promote Paket through Fable we can consider it :)

**Comment by forki** [comment] 2017-04-13 15:52
The thing is: it already failed to install on my machine because of
neverget

Am 13.04.2017 5:07 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by MangelMaxime** [comment] 2017-04-13 17:46
I myself add the same problem on the computer at work due to their nuget configuration.

So, it's could make sense.

**Comment by alfonsogarciacaro** [comment] 2017-04-13 21:26
I know, I know... my main concern is adding Paket to the template adds extra cognitive overhead for people who are not used to F# ecosystem. Paket brings many things with it:

- MONO dependency
- `paket.dependencies` and `paket.references` files
- `.paket folder` with extra files
- Auto generated: `paket.lock`, `packages` folder

And there would probably some questions pending:

- How do you run Paket? The convention is to use a build script, but this adds two more files (for Windows and Unix).
- Adding `Nuget.config` #75 didn't solve the issue?
- The Fable references (fable-elmish, fable-powerpack...) are also projects with the same Nuget references, to make Paket addition effective, we would have to add it as a convention for ALL Fable libraries.
- You would still have to use `dotnet restore` to get the FSharp.Net.Sdk and the CLI tool (dotnet-fable).
- The last point brings the other question, unfortunately adding Paket wouldn't remove Nuget completely which means that you could still have problems.

Hehe, now I look like MSFT giving @forki excuses to avoid Paket integration ;) Maybe @enricosada could weight in?

**Comment by et1975** [comment] 2017-04-13 22:46
Those are all excellent points, @alfonsogarciacaro!
I think If we leave the template and samples relying on "noget" and switch elmish itself it would be a satisfactory balance. 
@forki what do you think?

**Comment by forki** [comment] 2017-04-14 11:48
I think you are doing mistake, but that's fine. I can always convert
myself.

Alfonso why do you think a build script would be needed? It's just dotnet
restore. There is no change in default workflow at all.

Am 14.04.2017 12:46 vorm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

**Comment by alfonsogarciacaro** [comment] 2017-04-14 19:20
@forki I think I made my questions look rhetorical but they are actually honest ones ;) I don't know well how Paket 4 works with dotnet SDK, my assumptions come from looking at fable-suave-scaffold. So `dotnet restore` then is enough to activate Paket, there's no need to call `[mono] .paket/paket.exe restore`?

Also, won't there still be Nuget problems with FSharp.NET.Sdk and dotnet-fable (the CLI tool) even after adding Paket?

**Comment by forki** [comment] 2017-04-15 06:59
Yes no need to call paket.exe restore. It's the same workflow as before.

Regarding mono and the sdks - currently there is work going on to put paket
itself into an sdk and make it work with coreclr. This will allow us to
remove nuget completely. We will get there.

Am 14.04.2017 9:20 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by MangelMaxime** [comment] 2017-04-15 15:43
I am in favor of using paket.

For example, I forgot to put fable-core with the `next` tag.

As user install the newer version of fable-narumi the build process is broken because we installed an older version of fable-core.

![image](https://cloud.githubusercontent.com/assets/4760796/25064817/f068a2a6-2202-11e7-9d94-622933da1912.png)

**Comment by mizzle-mo** [comment] 2017-04-15 15:45
Paket is not that much mental overhead for the types of people that are going to be looking at this project.  The benefits of making this small teams life easier are worth the price IMO.  We don't want to be troubleshooting version conflicts in Gitter like I just did with @forki, also the only reason I was able to help him is I hit the same problem last night.  I am sending a PR to fix this specific issue.  We need something better long term though.  I vote for lock files.

**Comment by mizzle-mo** [comment] 2017-04-15 15:46
Also, just like 90% of the other JS projects out there, we need to recommend yarn as the path forward, and yarn should be used internally everywhere as well, if it's not already.  Just my $0.02

**Comment by johlrich** [comment] 2017-04-15 15:50
My 2c: I'm good with either Paket+Yarn or Npm+Nuget for now (with a long term personal pref towards Paket+Yarn w/ locks once the concerns above are done being addressed)

Biggest thing I would avoid Paket+Npm or Nuget+Yarn combos so we don't have one package manager locking and one not.

**Comment by enricosada** [comment] 2017-04-15 16:21
Also for me is a good idea to use paket, but not now, in the medium term. after a bit of testing.

But i think is better for now to just use default sdk.
And wait a bit to consolidate the new sdk with paket, and add that later. is not just paket who is new for sdk, also f# sdk is ok but young.

because too much new things, are hard to debug and give more corner cases.

**Comment by alfonsogarciacaro** [comment] 2017-04-15 22:18
@MangelMaxime About lock files, I completely agree they're necessary to have reproducible builds. Just I'm not sure whether they should be included in the templates (but I might be wrong), because it's good that users starting a project with a template download the latest version of the tools within a major (or minor) version range. Particularly at this point when we are continuously adding fixes.

**Comment by Pauan** [comment] 2017-04-16 00:10
@alfonsogarciacaro I can understand your viewpoint, but I think reproducible builds are also useful for templates: imagine new users trying out the template but then it doesn't work because the newer version breaks something. :scream:

This isn't just hypothetical, it happens all the time, not just with Fable but with PureScript as well. Having reproducible builds is always useful, *especially* as a new user, because then the new user is **guaranteed** to have a working template.

The last thing a new user wants is to have to deal with weird bugs and broken builds. That's guaranteed to turn people away. I speak from experience when I say that the lack of lockfiles has turned people away from PureScript.

**Comment by forki** [comment] 2017-04-16 06:18
@johlrich's point is very true. Currently we lock with yarn and don't lock on nuget side. This is the worst of all ideas. Not only from conceptual standpoint but also from very practical. This means that node packages are locked to something "old" but nuget draws newest. This means we will create trouble with incompatibility.

**Comment by MangelMaxime** [comment] 2017-04-16 07:50
For now,
I will remove the yarn.lock file from the template. Should be ok has long as no new version break something :)

When we are ready, we will add the paket.lock and the yarn.lock if we decide to use both of this tools. :)

**Comment by et1975** [comment] 2017-05-03 12:20
>Currently we lock with yarn and don't lock on nuget side. This is the worst of all ideas

I'm starting to see that @forki is right and that all the samples should be using paket + yarn. The worst first experience is when you checkout something that was known to build and find you have to figure out why your dependencies are broken.

**Comment by forki** [comment] 2017-05-03 12:23
welcome to the pain of nuget!

**Comment by mizzle-mo** [comment] 2017-05-15 21:02
+1 lock files should be used and checked into source control.  I would rather users be missing a few fixes and decide to manually upgrade rather than starting off with a broken template, because at that point we probably lost them as a user.  We can publish the templates more often if need be.

**Comment by mizzle-mo** [comment] 2017-05-15 21:13
@alfonsogarciacaro Wanted to add that I hit this problem too where the template failed when it was just working the day before.  Also, we have had to help multiple people with deps issues in Gitter.

**Comment by et1975** [comment] 2017-05-15 21:29
Thanks to @alfonsogarciacaro all fable dependencies (compiler + libs) will be via paket. Yarn will be used only by end-user apps and only for JS libs, with the lock file committed. That should solve all the problems of reproducible builds. See the work already done in "nuget" branch.

**Closed by et1975** 2017-05-15 21:29 UTC

**Comment by forki** [comment] 2017-05-16 08:16
I think with that distinction we can actually tell people what's going on
again. Kudos!

Am 15.05.2017 11:29 nachm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

Thanks to @alfonsogarciacaro <https://github.com/alfonsogarciacaro> all
fable dependencies (compiler + libs) will be via paket. Yarn will be used
only by end-user apps and only for JS libs, with the lock file committed.
That should solve all the problems of reproducible builds. See the work
already done in "nuget" branch.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-elmish/elmish/issues/76#issuecomment-301610498>,
or mute the thread
